# Generated by Django 4.2.15 on 2024-10-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name of affiliation', null=True, verbose_name='name of affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_review', models.CharField(db_column='title of review', null=True, verbose_name='title of review')),
                ('date', models.DateField(db_column='date of publication', null=True, verbose_name='date of publication')),
                ('title', models.CharField(db_column='title of article', null=True, verbose_name='title of article')),
                ('abstract', models.TextField(db_column='abstract', null=True, verbose_name='abstract')),
                ('pmid', models.IntegerField(db_column='pubmed id', null=True, verbose_name='pubmed id')),
                ('doi', models.CharField(db_column='doi', null=True, verbose_name='doi')),
                ('disclosure', models.TextField(db_column='conflict of interest', null=True, verbose_name='conflict of interest')),
                ('mesh_terms', models.TextField(db_column='mesh terms', null=True, verbose_name='mesh terms')),
                ('url', models.CharField(db_column='url', max_length=200, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name of author', null=True, verbose_name='name of author')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.affiliations')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='polls.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.authors')),
            ],
            options={
                'unique_together': {('article', 'author', 'affiliation')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', through='polls.Authorship', to='polls.authors'),
        ),
    ]
