# Generated by Django 4.2.15 on 2024-09-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors_names', models.CharField(max_length=200)),
                ('affilations', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=200)),
                ('review_title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=200)),
                ('pmid', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=200)),
                ('disclosure', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('impact_factor', models.FloatField(default=0)),
                ('issn', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quoted_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pmid', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.article')),
            ],
        ),
        migrations.CreateModel(
            name='Mesh_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.review'),
        ),
    ]
