# Generated by Django 4.2.15 on 2024-09-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pmid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quoted_by',
            name='pmid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='issn',
            field=models.IntegerField(),
        ),
    ]
