# Generated by Django 4.2.15 on 2024-10-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='name of affiliation', null=True, verbose_name='name of affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name of author', null=True, verbose_name='name of author')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.affiliations')),
            ],
        ),
        migrations.CreateModel(
            name='Cited_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=200, null=True, verbose_name='doi')),
                ('pmid', models.IntegerField(null=True, verbose_name='pubmed id')),
                ('url', models.CharField(max_length=200, null=True, verbose_name='url')),
            ],
        ),
        migrations.RemoveField(
            model_name='quoted_by',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='affilations',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors_names',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='review',
        ),
        migrations.RemoveField(
            model_name='article',
            name='review_title',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(db_column='date of publication', null=True, verbose_name='date of publication'),
        ),
        migrations.AddField(
            model_name='article',
            name='mesh_terms',
            field=models.TextField(db_column='mesh terms', null=True, verbose_name='mesh terms'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_review',
            field=models.CharField(db_column='title of review', null=True, verbose_name='title of review'),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(db_column='url', max_length=200, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(db_column='abstract', null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='article',
            name='disclosure',
            field=models.TextField(db_column='conflict of interest', null=True, verbose_name='conflict of interest'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(db_column='doi', null=True, verbose_name='doi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pmid',
            field=models.IntegerField(db_column='pubmed id', null=True, verbose_name='pubmed id'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_column='title of article', null=True, verbose_name='title of article'),
        ),
        migrations.DeleteModel(
            name='Mesh_terms',
        ),
        migrations.DeleteModel(
            name='Quoted_by',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='cited_by',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.article', verbose_name='article id'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='polls.article'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.authors'),
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', through='polls.Authorship', to='polls.authors'),
        ),
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together={('article', 'author', 'affiliation')},
        ),
    ]
