# Generated by Django 5.1.3 on 2024-11-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(db_column='doi', max_length=200, null=True, verbose_name='doi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='term',
            field=models.CharField(db_column='term', max_length=200, null=True, verbose_name='term'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_column='title of article', max_length=2000, null=True, verbose_name='title of article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_review',
            field=models.CharField(db_column='title of review', max_length=2000, null=True, verbose_name='title of review'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(db_column='name of author', max_length=2000, null=True, verbose_name='name of author'),
        ),
    ]
