# Generated by Django 5.1.4 on 2025-03-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_article_doi_alter_article_term_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'gene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Xref',
            fields=[
                ('xref_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'xref',
                'managed': False,
            },
        ),
    ]
