# Generated by Django 4.2.15 on 2024-09-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_article_pmid_alter_quoted_by_pmid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='affilations',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors_names',
        ),
        migrations.RemoveField(
            model_name='article',
            name='review_title',
        ),
        migrations.RemoveField(
            model_name='quoted_by',
            name='review_title',
        ),
        migrations.AddField(
            model_name='quoted_by',
            name='review',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.review'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Author_affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.affiliation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.author')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.author_affiliation'),
            preserve_default=False,
        ),
    ]
