# Generated by Django 4.2.15 on 2024-09-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_affiliation_author_remove_article_affilations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cited_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=200, null=True)),
                ('pmid', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='author_affiliation',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='author_affiliation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mesh_terms',
            name='article',
        ),
        migrations.RemoveField(
            model_name='quoted_by',
            name='article',
        ),
        migrations.RemoveField(
            model_name='quoted_by',
            name='review',
        ),
        migrations.AddField(
            model_name='article',
            name='author_affiliation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='mesh_terms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_review',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='abbreviation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='disclosure',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pmid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.review'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='impact_factor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='issn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Author_affiliation',
        ),
        migrations.DeleteModel(
            name='Mesh_terms',
        ),
        migrations.DeleteModel(
            name='Quoted_by',
        ),
        migrations.AddField(
            model_name='cited_by',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.article'),
        ),
        migrations.AddField(
            model_name='cited_by',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.review'),
        ),
    ]
