# Generated by Django 5.1.4 on 2025-03-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_gene_xref'),
    ]

    operations = [
        migrations.CreateModel(
            name='RnaPrecomputed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rna_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rnc_rna_precomputed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lineage', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rnc_taxonomy',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
        migrations.DeleteModel(
            name='Xref',
        ),
    ]
