# Generated by Django 5.1.6 on 2025-03-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rnaprecomputed_taxonomy_delete_gene_delete_xref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesWithAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_review', models.CharField(db_column='title of review', max_length=2000, null=True, verbose_name='title of review')),
                ('date', models.DateField(db_column='date of publication', null=True, verbose_name='date of publication')),
                ('title', models.CharField(db_column='title of article', max_length=2000, null=True, verbose_name='title of article')),
                ('abstract', models.TextField(db_column='abstract', null=True, verbose_name='abstract')),
                ('pmid', models.IntegerField(db_column='pubmed id', null=True, verbose_name='pubmed id')),
                ('doi', models.CharField(db_column='doi', max_length=200, null=True, verbose_name='doi')),
                ('disclosure', models.TextField(db_column='conflict of interest', null=True, verbose_name='conflict of interest')),
                ('mesh_terms', models.TextField(db_column='mesh terms', null=True, verbose_name='mesh terms')),
                ('url', models.CharField(db_column='url', max_length=200, null=True, verbose_name='url')),
                ('term', models.CharField(db_column='term', max_length=200, null=True, verbose_name='term')),
                ('affiliations_by_author', models.JSONField(db_column='authors', null=True, verbose_name='authors')),
            ],
        ),
    ]
