# Generated by Django 4.2.15 on 2024-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_cited_by_remove_author_affiliation_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True),
        ),
    ]
