# Generated by Django 4.2.15 on 2024-09-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_article_authors_alter_article_disclosure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mesh_terms',
            field=models.TextField(null=True),
        ),
    ]
