# Generated by Django 4.2.15 on 2024-09-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_article_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_affiliation',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.CreateModel(
            name='Articles_authors_affiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.affiliations')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.article')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.authors')),
            ],
        ),
    ]
