# Generated by Django 4.2.15 on 2024-09-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_affiliations_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliations',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
