# Generated by Django 4.2.15 on 2024-09-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_affiliations_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='review',
        ),
        migrations.RemoveField(
            model_name='cited_by',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
