# Generated by Django 4.2.15 on 2024-09-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_article_review_remove_cited_by_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliations',
            name='name',
            field=models.TextField(null=True, verbose_name='affiliation name'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='article',
            name='disclosure',
            field=models.TextField(null=True, verbose_name='conflict of interest'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.TextField(null=True, verbose_name='doi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='mesh_terms',
            field=models.TextField(null=True, verbose_name='mesh terms'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pmid',
            field=models.IntegerField(null=True, verbose_name='pubmed id'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(null=True, verbose_name='article title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_review',
            field=models.TextField(null=True, verbose_name='review title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=200, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='articles_authors_affiliations',
            name='affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.affiliations', verbose_name='affiliation'),
        ),
        migrations.AlterField(
            model_name='articles_authors_affiliations',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.article', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='articles_authors_affiliations',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.authors', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='author name'),
        ),
        migrations.AlterField(
            model_name='cited_by',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.article', verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='cited_by',
            name='doi',
            field=models.CharField(max_length=200, null=True, verbose_name='doi'),
        ),
        migrations.AlterField(
            model_name='cited_by',
            name='pmid',
            field=models.IntegerField(null=True, verbose_name='pubmed id'),
        ),
        migrations.AlterField(
            model_name='cited_by',
            name='url',
            field=models.CharField(max_length=200, null=True, verbose_name='url'),
        ),
    ]
