# Generated by Django 4.2.15 on 2024-09-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_affiliations_name_alter_article_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.TextField(null=True, verbose_name='author name'),
        ),
    ]
