# Generated by Django 4.2.15 on 2024-09-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_authors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliations',
            name='name',
            field=models.TextField(db_column='name of affiliation', null=True, verbose_name='name of affiliation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(db_column='abstract', null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='article',
            name='disclosure',
            field=models.TextField(db_column='conflict of interest', null=True, verbose_name='conflict of interest'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.TextField(db_column='doi', null=True, verbose_name='doi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='mesh_terms',
            field=models.TextField(db_column='mesh terms', null=True, verbose_name='mesh terms'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pmid',
            field=models.IntegerField(db_column='pubmed id', null=True, verbose_name='pubmed id'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(db_column='date of publication', null=True, verbose_name='date of publication'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(db_column='title of article', null=True, verbose_name='title of article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_review',
            field=models.TextField(db_column='review_title', null=True, verbose_name='review title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(db_column='url', max_length=200, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.TextField(db_column='name of author', null=True, verbose_name='name of author'),
        ),
        migrations.AlterField(
            model_name='cited_by',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.article', verbose_name='article id'),
        ),
    ]
