# Generated by Django 4.2.15 on 2024-09-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_article_title_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_review',
            field=models.TextField(db_column='title of review', null=True, verbose_name='title of review'),
        ),
    ]
