# Generated by Django 4.2.15 on 2024-09-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_article_title_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(to='polls.authors'),
        ),
        migrations.AddField(
            model_name='authors',
            name='affiliations',
            field=models.ManyToManyField(to='polls.affiliations'),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(db_column='doi', null=True, verbose_name='doi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_column='title of article', null=True, verbose_name='title of article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_review',
            field=models.CharField(db_column='title of review', null=True, verbose_name='title of review'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(db_column='name of author', null=True, verbose_name='name of author'),
        ),
        migrations.DeleteModel(
            name='Articles_authors_affiliations',
        ),
    ]
