# Generated by Django 4.2.15 on 2024-09-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_article_authors_authors_affiliations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='date',
        ),
    ]
