# Generated by Django 4.2.15 on 2024-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_rename_pub_date_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', to='polls.authors'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='affiliations',
            field=models.ManyToManyField(related_name='authors', to='polls.affiliations'),
        ),
    ]
