# Generated by Django 4.2.15 on 2024-09-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_article_authors_alter_authors_affiliations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='article', to='polls.authors'),
        ),
    ]
