# # az login
# # az group create --name devia25 --location francecentral
# # az acr login --name pubmedregistry

# apiVersion: 2021-09-01
# location: francecentral
# name: pubmed-container-group
# properties:
#   # imageRegistryCredentials:
#   #   - server: ${{ secrets.REGISTRY_SERVER }}
#   #     username: ${{ secrets.REGISTRY_USERNAME }}
#   #     password: ${{ secrets.REGISTRY_PASSWORD }}
#   containers:
#   - name: django
#     properties:
#       image: joachimlombardi/django:latest
#       resources:
#         requests:
#           cpu: 0.5
#           memoryInGB: 1
#       ports:
#       - port: 8000
#       environmentVariables:
#         - name: DJANGO_SETTINGS_MODULE
#           value: pubmed_analyze.settings
#         - name: ALLOWED_HOSTS
#           value: ${{ secrets.ALLOWED_HOSTS }}
#         - name: DATABASE_HOST
#           value: ${{ secrets.DATABASE_HOST }}
#         - name: DATABASE_PORT
#           value: ${{ secrets.DATABASE_PORT }}
#         - name: DATABASE_USER
#           value: ${{ secrets.DATABASE_USER }}
#         - name: DATABASE_URL
#           value: ${{ secrets.DATABASE_URL }}
#         - name: DATABASE_PASSWORD
#           value: ${{ secrets.DATABASE_PASSWORD }}
#         - name: DATABASE_NAME
#           value: ${{ secrets.DATABASE_NAME }}
#         - name: EMAIL_HOST_USER
#           value: ${{ secrets.EMAIL_HOST_USER }}
#         - name: EMAIL_HOST_PASSWORD
#           value: $ {{ secrets.EMAIL_HOST_PASSWORD }}
#         - name: OPENAI_API_KEY
#           value: ${{ secrets.OPENAI_API_KEY }}
#         - name: ERROR_NOTIFICATION_EMAIL
#           value: ${{ secrets.ERROR_NOTIFICATION_EMAIL }}
#         - name: DEFAULT_FROM_EMAIL
#           value: ${{ secrets.DEFAULT_FROM_EMAIL }}
#         - name: DJANGO_SUPERUSER_USERNAME
#           value: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
#         - name: DJANGO_SUPERUSER_EMAIL
#           value: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
#         - name: DJANGO_SUPERUSER_PASSWORD
#           value: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}

#   - name: postgres
#     properties:
#       image: joachimlombardi/postgres:16
#       resources:
#         requests:
#           cpu: 0.5
#           memoryInGB: 1
#       ports:
#       - port: 5432
#       environmentVariables:
#         - name: DATABASE_USER
#           value: ${{ secrets.DATABASE_USER }}
#         - name: DATABASE_PASSWORD
#           value: ${{ secrets.DATABASE_PASSWORD }}
#         - name: DATABASE_NAME
#           value: ${{ secrets.DATABASE_NAME }}

#   - name: elasticsearch
#     properties:
#       image: joachimlombardi/elasticsearch:latest
#       resources:
#         requests:
#           cpu: 1
#           memoryInGB: 2
#       ports:
#       - port: 9200

#   - name: grafana
#     properties:
#       image: joachimlombardi/grafana:latest
#       resources:
#         requests:
#           cpu: 0.25
#           memoryInGB: 0.5
#       ports:
#       - port: 3000

#   - name: ollama
#     properties:
#       image: joachimlombardi/ollama:latest
#       resources:
#         requests:
#           cpu: 1
#           memoryInGB: 2
#       ports:
#       - port: 11434

#   - name: prometheus
#     properties:
#       image: joachimlombardi/prometheus:latest
#       resources:
#         requests:
#           cpu: 0.25
#           memoryInGB: 0.5
#       ports:
#       - port: 9090
  
#   - name: uptime-kuma
#     properties:
#       image: joachimlombardi/uptime-kuma:latest
#       resources:
#         requests:
#           cpu: 0.5
#           memoryInGB: 1
#       ports:
#       - port: 3001


#   osType: Linux
#   restartPolicy: Always
#   ipAddress:
#     type: Public
#     dnsNameLabel: pubmed-containers
#     ports:
#     - protocol: TCP
#       port: 8000  
#     - protocol: TCP
#       port: 3000
#     - protocol: TCP
#       port: 3001
