# Dockerfile.dependencies
# docker login
# docker build -f Dockerfile.dependencies -t joachimlombardi/pubmed_dependencies:latest .
# docker push joachimlombardi/pubmed_dependencies:latest

FROM python:3.11.8

WORKDIR /pubmed_analyze

# Copier uniquement le fichier requirements.txt
COPY ./requirements.txt /pubmed_analyze/requirements.txt

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt
