
# docker-compose --env-file .env up --build
# docker exec -it django bash


services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django 
    command: >
      /bin/bash -c "
        if python manage.py showmigrations | grep '\[ \]'; then
          echo 'Migrations en attente, application...'
          python manage.py makemigrations
          python manage.py migrate
        else
          echo 'Aucune migration en attente.'
        fi
        if python manage.py shell -c \"from django.contrib.auth import get_user_model; print(get_user_model().objects.filter(is_superuser=True).exists())\" | grep -q 'False'; then
          echo 'Création du superutilisateur...'
          python manage.py createsuperuser --noinput
        else
          echo 'Superutilisateur déjà existant.'
        fi
<<<<<<< HEAD
        if ! python manage.py shell -c \"from pubmed_analyze.models import Article; exit(1 if Article.objects.exists() else 0)\"; then
=======
        if ! python manage.py shell -c \"from .models import Article; exit(1 if Article.objects.exists() else 0)\"; then
>>>>>>> 3db89d36 (function_call_code)
          echo 'Ajout des articles à la base de données...'
          python manage.py commands article_to_database
        else
          echo 'Les articles sont déjà ajoutés.'
        fi
<<<<<<< HEAD
        if ! python manage.py shell -c \"from pubmed_analyze.models import ArticlesWithAuthors; exit(1 if ArticlesWithAuthors.objects.exists() else 0)\"; then
=======
        if ! python manage.py shell -c \"from .models import ArticlesWithAuthors; exit(1 if ArticlesWithAuthors.objects.exists() else 0)\"; then
>>>>>>> 3db89d36 (function_call_code)
        echo 'Ajout des articles avec auteurs à la base de données...'
        python manage.py commands article_full_to_database
        else
          echo 'Les articles avec auteurs sont déjà ajoutés.'
        fi
        if ! python manage.py shell -c \"from django_elasticsearch_dsl.registries import registry; exit(1 if registry.get_documents() else 0)\"; then
          echo 'Indexation des articles...'
          python manage.py commands index_articles
        else
          echo 'Les articles sont déjà indexés.'
        fi
        echo 'Démarrage du serveur Django...'
        python manage.py runserver 0.0.0.0:8000
      "
    container_name: django
    ports:
      - "8000:8000" 
    environment:
      - DJANGO_SETTINGS_MODULE=pubmed_analyze.settings 
      - DATABASE_URL=${DATABASE_URL} 
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ERROR_NOTIFICATION_EMAIL=${EMAIL_HOST_USER}
      - DEFAULT_FROM_EMAIL=${EMAIL_HOST_USER}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${EMAIL_HOST_USER}
      - DJANGO_SUPERUSER_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ..:/pubmed_analyze  
    depends_on:
      - elasticsearch  
      - prometheus
      - db 
      - ollama 


  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - ./_data/elasticsearch_data:/usr/share/elasticsearch/data


  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    container_name: elasticsearch_exporter
    ports:
      - "9114:9114"
    command:
      - '--es.uri=http://elasticsearch:9200'
    depends_on:
      - elasticsearch
  

  # Service pour PostgreSQL
  db:
    image: postgres:16
    container_name: db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - default


  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: postgres_exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?sslmode=disable
    depends_on:
      - db


  ollama:
    image: ollama/ollama:latest 
    container_name: ollama
    ports:
      - "11434:11434" 
    volumes:
      - ../../ollama_models:/root/.ollama/models  
    restart: always
    environment:
      - OLLAMA_NUM_PARALLEL=1


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
      - ./data/prometheus:/prometheus
    ports:
      - "9090:9090" 


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=${EMAIL_HOST_USER}
      - GF_SMTP_PASSWORD=${EMAIL_HOST_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${EMAIL_HOST_USER}
      - GF_SMTP_FROM_NAME=Grafana
    depends_on:
      - prometheus
      - renderer


  # Service pour Grafana Image Renderer
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    ports:
      - "8081:8081"


  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime_kuma
    ports:
      - "3001:3001" 
    volumes:
      - ./data/uptime-kuma:/pubmed_analyze/data  
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    depends_on:
      - prometheus  


  node-exporter:
      image: prom/node-exporter:latest
      container_name: node-exporter
      restart: unless-stopped
      ports:
        - "9100:9100"
      networks:
        - default

networks:
  default:
    name: django_network