# prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch_exporter:9114']
  # - job_name: 'ollama'
  #   static_configs:
  #     - targets: ['ollama:11434']
  - job_name: 'db'
    static_configs:
      - targets: ['postgres_exporter:9187']  

