# prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets: ['django:8000']  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch_exporter:9114']
  - job_name: 'db'
    static_configs:
      - targets: ['postgres_exporter:9187'] 
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100'] 
  - job_name: 'uptime_kuma'
    static_configs:
      - targets: ['uptime-kuma:3001']
    basic_auth:
      username: Joachim
      password: JsbhUgmGY7GRpzW

