name: Django CI/CD with Docker Compose

on:
  push:
    branches:
      - master  # ou une branche principale spécifique
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug environment inside container
      run: docker exec django env
    
    # Étape pour installer Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Vérification de l'installation de Docker Compose
    - name: Check Docker Compose version
      run: docker-compose --version

    # Étape pour construire et démarrer les services avec Docker Compose
    - name: Build and start services with Docker Compose
      run: docker-compose -f pubmed_analyze/docker/docker-compose.yml up --build -d

    - name: Limit resources for Django container
      run: |
        docker container update --memory 4g --memory-swap 4g django
      
    # Exécuter les tests avec Docker Compose
    - name: Run tests
      run: docker exec django python manage.py test polls --pattern="test_*.py"

      # Étape pour afficher les logs en cas d'échec
    - name: Display logs if tests fail
      if: failure()
      run: docker logs django

    # Étape pour arrêter les services après les tests
    - name: Stop services
      run: docker-compose -f pubmed_analyze/docker/docker-compose.yml down



