name: Django CI/CD with Docker Compose

on:
  push:
    branches:
      - master  # ou une branche principale spécifique
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and start services with Docker Compose
      run: |
        docker-compose up --build -d
    
    - name: Run tests
      run: docker-compose exec django python manage.py test

    - name: Stop services
      run: docker-compose down
