name: Django CI/CD with Docker Compose

on:
  push:
    branches:
      - master  # ou une branche principale spécifique
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Inspect file structure
      run: ls -R $GITHUB_WORKSPACE


    # Étape pour installer Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Vérification de l'installation de Docker Compose
    - name: Check Docker Compose version
      run: docker-compose --version

    # Étape pour construire et démarrer les services avec Docker Compose
    - name: Build and start services with Docker Compose
      working-directory: /pubmed_analyze
      run: |
        docker-compose --env-file ./docker/.env up --build -d

    # Exécuter les tests avec Docker Compose
    - name: Run tests
      working-directory: $GITHUB_WORKSPACE/pubmed_analyze
      run: docker-compose exec django python $GITHUB_WORKSPACE/pubmed_analyze/manage.py test $GITHUB_WORKSPACE/pubmed_analyze/polls

    # Étape pour arrêter les services après les tests
    - name: Stop services
      working-directory: $GITHUB_WORKSPACE/pubmed_analyze
      run: docker-compose down



