name: Django CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}
          POSTGRES_USER: ${{secrets.DATABASE_USER}}
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'  

    - name: Install dependencies
      run: |
        pip install -r pubmed_analyze/docker/requirements.txt

    - name: Run tests
      run: |
        python pubmed_analyze/manage.py test pubmed_analyze/polls/tests   
      env:
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        DJANGO_SETTINGS_MODULE: pubmed_analyze.pubmed_analyze.settings  
