name: Django CI

on:
  push:
    branches:
      - main  # ou une branche spécifique
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> $GITHUB_ENV
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
        echo "DATABASE_HOST=localhost" >> $GITHUB_ENV  # Par défaut dans l'environnement de CI
        echo "DATABASE_PORT=5432" >> $GITHUB_ENV

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances du projet

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test  # Exécute vos tests unitaires

